### ISSUE TITLE
Unhandled Promies Rejection

### ISSUE THREAD

**Issue by ghost** [schroffl/teamspeak-query#2]
```
(node:9620) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): [object Object]
(node:9620) DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

Node Version 7

**Comment by schroffl** [comment]
This just means that you always need to provide a rejection handler via `catch`.

**Comment by ghost** [comment]
oh, tbh i never worked with reject, can you give me an example?

**Comment by schroffl** [comment]
Could you maybe comment your code? I'll try to explain what you have to do...

**Comment by ghost** [comment]
pretty much the example you provided in the readme

```js
const query = module.exports = new (require('teamspeak-query'))('127.0.0.1', 10011);

query.send('login', 'serveradmin', 'pw')
	.then(() => query.send('use', 1))
	.then(() => query.send('servernotifyregister', {'event': 'server'}))
	.catch(err => console.log(err));

query.send('clientlist', data => console.log(data));
```

**Comment by schroffl** [comment]
You don't pass a handler in your last line:

```javascript
query.send('clientlist', data => console.log(data));
```

But there's another issue with your code. Getting the clientlist won't work, because at the time the module sends the `clientlist` command to the teamspeak server, the server has probably not yet responded to the login. That has something to do with JavaScript's asynchronous nature .
Thus you have to wait until all the previous commands have finished (or produced an error). That can be achieved by inserting your last line into the promise chain:

```javascript
const query = module.exports = new (require('teamspeak-query'))('127.0.0.1', 10011);

query.send('login', 'serveradmin', 'pw')
    .then(() => query.send('use', 1))
    .then(() => query.send('servernotifyregister', {'event': 'server'}))
    .then(() => query.send('clientlist'))
    .then(console.log)
    .catch(err => console.log(err));
```

**Edit:** I just noticed something else: It seems like you're trying to pass a callback to `query.send`. Promises, which this library uses, are basically alternatives to using callbacks. But they both have their advantages and disadvantages. [This article](https://developers.google.com/web/fundamentals/getting-started/primers/promises) should give you a basic idea about Promises. And as always: Google is your friend ;)
